# Generated by Django 4.2.13 on 2024-05-28 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lmsApp", "0006_delete_student_lesson_user_note_user_week_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="user",
        ),
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
        migrations.RemoveField(
            model_name="week",
            name="user",
        ),
        migrations.RemoveField(
            model_name="weekpdf",
            name="user",
        ),
    ]
