# Generated by Django 4.2.13 on 2024-05-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lmsApp", "0008_lesson_user_note_user_week_user_weekpdf_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="lesson",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lmsApp.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="week",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="lmsApp.week"
            ),
        ),
        migrations.AlterField(
            model_name="week",
            name="lesson",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lmsApp.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="weekpdf",
            name="week",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="lmsApp.week"
            ),
        ),
    ]
