# Generated by Django 4.2.13 on 2024-05-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lmsApp", "0009_alter_note_lesson_alter_note_week_alter_week_lesson_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lmsApp.lesson"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lmsApp.week"
            ),
        ),
        migrations.AlterField(
            model_name="week",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lmsApp.lesson"
            ),
        ),
        migrations.AlterField(
            model_name="weekpdf",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lmsApp.week"
            ),
        ),
    ]
