# Generated by Django 4.2.13 on 2024-05-28 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lmsApp", "0012_rename_event_date_event_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="theme",
        ),
    ]
