# Generated by Django 4.2.13 on 2024-05-29 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lmsApp", "0013_remove_event_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weekpdf",
            name="user",
        ),
    ]
