# Generated by Django 5.2 on 2025-04-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0015_weekpdf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekpdf',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
