# Generated by Django 5.2 on 2025-05-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0017_note_ai_questions_note_ai_summary_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularNoteTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsApp.lesson')),
            ],
        ),
    ]
