# Generated by Django 5.2 on 2025-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0018_popularnotetitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularnotetitle',
            name='lesson',
        ),
        migrations.AddField(
            model_name='popularnotetitle',
            name='lesson_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
