# Generated by Django 5.2 on 2025-05-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0019_remove_popularnotetitle_lesson_and_more'),
    ]

    operations = [
    ]
