# Generated by Django 5.2 on 2025-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmsApp", "0021_alter_note_options_note_created_note_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["-created", "-updated"]},
        ),
        migrations.AddField(
            model_name="lesson",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
